"use client";

import { Sparkles } from "lucide-react";
import { useT } from "@/lib/i18n/provider";
import { cn } from "@/lib/utils";

export function AiDisclaimer({ className }: { className?: string }) {
  const t = useT();
  return (
    <p className={cn("flex items-start gap-2 text-xs text-muted-foreground", className)}>
      <Sparkles className="mt-0.5 size-3.5 shrink-0" />
      <span>{t("Generated by AI as assistance. It is a starting point, not scientific validation — review and edit it yourself.")}</span>
    </p>
  );
}
